[project]
name = "PyPackage-Builder"
version = "0.3.0"
description = "A simple package builder for python packages managed by Pixi"
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
license = "MIT"
readme = "README.md"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]

[environments]
dev = { features = ["lint"] }
publish = { features = ["release"] }

[dependencies]
copier = ">=9.2.0,<9.3"

[feature.lint.dependencies]
ruff = ">=0.4.4,<0.5"
pre-commit-hooks = ">=4.6.0,<4.7"
pre-commit = ">=3.7.1,<3.8"
yamllint = ">=1.35.1,<1.36"

[feature.lint.tasks]
style = { cmd = "ruff check ." }
_pre-commit_setup = { cmd = "pre-commit install" }
pre-commit_run = { cmd = "pre-commit run --all-files", depends-on = ["_pre-commit_setup"] }

[feature.release.dependencies]
python-semantic-release = ">=9.7.3,<9.8"

[feature.release.tasks]
semver = 'echo "Next Version is: $(semantic-release -c releaserc.toml version --print)"'
release = "semantic-release -c releaserc.toml version"
