---
name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, development]

jobs:
  ################################################################################################
  # Ruff: Run ruff linter
  ################################################################################################
  Ruff:
    runs-on: ubuntu-latest
    env:
      PIXI_ENV: "dev"
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.7.0
        with:
          environments: ${{ env.PIXI_ENV }}
          pixi-version: v0.22.0
          cache: false
          locked: false
          # cache-key: pixi-ENV_${{ env.PIXI_ENV }}-

      - name: Run Ruff
        run: pixi run style

  ################################################################################################
  # Semantic-Release: Run semantic-release to automate versioning and publishing
  ################################################################################################
  Semantic-Release:
    permissions:
      # Read releases read-all
      contents: write
      packages: write
      issues: write
      pull-requests: write

    # if pulling to main, deploy to PyPI
    if: github.ref == 'refs/heads/main'

    env:
      PIXI_ENV: "publish"

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    # Set up operating system
    runs-on: ${{ matrix.os }}

    # Concurrency is for preventing multiple runs of the same workflow
    concurrency: release

    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}

    # Define job steps
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.7.0
        env:
          RUNNER_DEBUG: true
        with:
          environments: ${{ env.PIXI_ENV }}
          pixi-version: v0.22.0
          cache: false
          locked: false
          # cache-key: pixi-ENV_${{ env.PIXI_ENV }}-

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: release
        run: pixi run release
